global:
  scrape_interval: 4s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [<##your server ip address:port no of your application>] 
      # IP of the server where the app is running